apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::422940076496:role/UdacityFlaskDeployCBKubectlRole
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-27T03:40:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "887"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: a5e23bf2-6fdc-11ea-9afb-0a49e52ebb46